spring.application.name=banking-config-server
server.port=8888

# Git repository containing configuration files
spring.cloud.config.server.git.uri=https://github.com/rohitgapat/Banking-System.git

# Configuration files are inside the config folder
spring.cloud.config.server.git.search-paths=config